"""Smoke tests for the direct-mode CLI in main.py."""

import contextlib
import io
import sys
import tempfile
import unittest
import warnings
from pathlib import Path
from unittest import mock

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import core
import db
import main
import parser as gcode_parser


def setUpModule():
    # db.py leaves sqlite connections open after its "with" blocks; the runner
    # enables the 'default' filter, which surfaces their ResourceWarning noise.
    warnings.filterwarnings(
        "ignore", message="unclosed database", category=ResourceWarning
    )


PRUSA_GCODE = """; generated by PrusaSlicer 2.7.4
; filament_type = PLA
G1 X10 Y10 E1 F1200
; filament used [mm] = 1500.50
; filament used [g] = 4.49
; estimated printing time (normal mode) = 1h 30m 15s
"""


class ParseArgsTests(unittest.TestCase):
    """main.parse_args argument parsing contract."""

    def test_defaults_when_no_arguments(self):
        args = main.parse_args([])
        self.assertIsNone(args.file_path)
        self.assertIsNone(args.spool)
        self.assertFalse(args.yes)

    def test_positional_file_path(self):
        args = main.parse_args(["part.gcode"])
        self.assertEqual(args.file_path, "part.gcode")
        self.assertIsNone(args.spool)
        self.assertFalse(args.yes)

    def test_spool_and_yes_flags(self):
        args = main.parse_args(["part.3mf", "--spool", "7", "--yes"])
        self.assertEqual(args.file_path, "part.3mf")
        self.assertEqual(args.spool, 7)
        self.assertTrue(args.yes)

    def test_short_yes_flag(self):
        args = main.parse_args(["part.gcode", "-y"])
        self.assertTrue(args.yes)

    def test_non_integer_spool_exits_with_code_two(self):
        stderr = io.StringIO()
        with contextlib.redirect_stderr(stderr):
            with self.assertRaises(SystemExit) as ctx:
                main.parse_args(["part.gcode", "--spool", "abc"])
        self.assertEqual(ctx.exception.code, 2)


class IsolatedCliTestCase(unittest.TestCase):
    """Shared setup: temporary database, seeded spool and slice file."""

    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.tmp = Path(tmp.name)
        self.db_path = self.tmp / "spooli.db"

        # Redirect every implicit database access to the temporary file.
        patcher = mock.patch.object(db, "get_db_path", return_value=self.db_path)
        patcher.start()
        self.addCleanup(patcher.stop)

        db.init_db()
        self.spool_id = db.create_spool(
            "PLA", brand="Sunlu", color="White", remaining_weight_g=1000.0,
            path=self.db_path,
        )
        self.gcode_path = self.tmp / "part.gcode"
        self.gcode_path.write_text(PRUSA_GCODE, encoding="utf-8")

    def run_direct(self, path_arg, auto_confirm, mock_input=None):
        # Capture stdout while optionally mocking builtins.input.
        stdout = io.StringIO()
        if mock_input is None:
            input_patch = contextlib.nullcontext()
        else:
            input_patch = mock.patch("builtins.input", **mock_input)
        with input_patch:
            with contextlib.redirect_stdout(stdout):
                code = main.run_direct_mode(path_arg, None, auto_confirm)
        return code, stdout.getvalue()


class DirectModeTests(IsolatedCliTestCase):
    """run_direct_mode end-to-end flow with mocked standard I/O."""

    def test_success_flow_records_print_and_deducts_spool(self):
        code, output = self.run_direct(str(self.gcode_path), auto_confirm=True)
        self.assertEqual(code, 0)
        self.assertIn("--- Resumen de impresión ---", output)
        self.assertIn("Bobina asignada: ID", output)
        self.assertIn("Impresión registrada correctamente con ID 1.", output)

        spool = db.get_spool_by_id(self.spool_id, self.db_path)
        self.assertAlmostEqual(spool["remaining_weight_g"], 1000.0 - 4.49, places=4)
        history = db.get_print_history(path=self.db_path)
        self.assertEqual(len(history), 1)
        self.assertEqual(history[0]["status"], "completed")
        self.assertEqual(history[0]["grams_used"], 4.49)

    def test_declined_confirmation_records_nothing(self):
        code, output = self.run_direct(
            str(self.gcode_path),
            auto_confirm=False,
            mock_input={"return_value": "n"},
        )
        self.assertEqual(code, 0)
        self.assertIn("Operación cancelada por el usuario.", output)
        self.assertEqual(db.get_print_history(path=self.db_path), [])
        spool = db.get_spool_by_id(self.spool_id, self.db_path)
        self.assertEqual(spool["remaining_weight_g"], 1000.0)

    def test_eof_on_confirmation_returns_one(self):
        code, output = self.run_direct(
            str(self.gcode_path),
            auto_confirm=False,
            mock_input={"side_effect": EOFError},
        )
        self.assertEqual(code, 1)
        self.assertIn("Operación cancelada por el usuario.", output)
        self.assertEqual(db.get_print_history(path=self.db_path), [])

    def test_missing_file_returns_one(self):
        code, output = self.run_direct(
            str(self.tmp / "absent.gcode"), auto_confirm=True
        )
        self.assertEqual(code, 1)
        self.assertIn("Error: no se encontró el archivo", output)


class SummaryTests(unittest.TestCase):
    """format_duration and display_summary output contracts."""

    def test_format_duration_cases(self):
        self.assertEqual(main.format_duration(3661), "1h 1m 1s")
        self.assertEqual(main.format_duration(65), "1m 5s")
        self.assertEqual(main.format_duration(9), "9s")
        self.assertEqual(main.format_duration(0), "0s")

    def test_display_summary_prints_costs_and_returns_remaining(self):
        metadata = gcode_parser.PrintMetadata(
            file_name="part.gcode",
            material="PLA",
            grams=10.0,
            length_mm=3333.0,
            duration_seconds=3661,
        )
        spool = {
            "id": 3,
            "brand": "Sunlu",
            "color": "White",
            "remaining_weight_g": 250.0,
        }
        costs = core.CostBreakdown(
            filament_cost=0.2, electricity_cost=0.04, total_cost=0.24
        )
        stdout = io.StringIO()
        with contextlib.redirect_stdout(stdout):
            remaining = main.display_summary(metadata, spool, costs, "$")
        output = stdout.getvalue()
        self.assertAlmostEqual(remaining, 240.0, places=4)
        self.assertIn("Archivo: part.gcode", output)
        self.assertIn("Duración estimada: 1h 1m 1s", output)
        self.assertIn("Bobina asignada: ID 3 (Sunlu White)", output)
        self.assertIn("Restante tras impresión: 240.00 g", output)
        self.assertIn("Costo total estimado: $0.2400", output)


class MainEntryTests(IsolatedCliTestCase):
    """main() entry point wiring on top of the isolated setup."""

    def test_is_first_run_tracks_database_existence(self):
        missing = self.tmp / "absent.db"
        with mock.patch.object(db, "get_db_path", return_value=missing):
            self.assertTrue(main.is_first_run())
        with mock.patch.object(db, "get_db_path", return_value=self.db_path):
            self.assertFalse(main.is_first_run())

    def test_main_with_yes_flag_records_print(self):
        stdout = io.StringIO()
        with contextlib.redirect_stdout(stdout):
            code = main.main([str(self.gcode_path), "--yes"])
        self.assertEqual(code, 0)
        self.assertIn("Impresión registrada correctamente con ID", stdout.getvalue())
        self.assertEqual(len(db.get_print_history(path=self.db_path)), 1)


if __name__ == "__main__":
    unittest.main()
