"""Characterisation tests for the metadata parser in parser.py."""

import io
import sys
import tempfile
import unittest
import zipfile
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import parser as gcode_parser

CURA_GCODE = """;FLAVOR:Marlin
;TIME:3031
;Filament used: 5.67m
;Layer height: 0.2
;MINX:75.0
G1 X10 Y10 E10 F1200
;End of Gcode
"""

PRUSASLICER_GCODE = """; generated by PrusaSlicer 2.7.4 on 2024-01-01 at 10:00:00 UTC
; filament_type = PLA
; filament_settings_id = Generic PLA @ Prusa
G1 X10 Y10 E1 F1200
; filament used [mm] = 1500.50
; filament used [g] = 4.49
; filament used [cm3] = 5.39
; filament cost = 0.45
; estimated printing time (normal mode) = 1h 30m 15s
"""

ORCASLICER_GCODE = """; generated by OrcaSlicer 2.0.0
; filament_type = "PETG"
G1 X10 Y10 E1 F1200
; filament used [mm] = 2750.00
; filament used [g] = 8.25
; total filament used [g] = 8.25
; total filament cost = 0.83
; estimated printing time (normal mode) = 2h 15m 30s
"""

BAMBU_STUDIO_GCODE = """; Bambu Studio 01.09.00.60
; filament_type = "PLA"
G1 X10 Y10 E1 F1200
; total filament used [g] = 10.31
; total filament cost = 1.03
; model printing time: 1h 10m 5s; estimation printing time (normal mode) = 1h 20m 5s
"""

BARE_GCODE = """G1 X0 Y0 E1 F1200
G1 X10 Y10 E2 F1200
"""


class TempDirTestCase(unittest.TestCase):
    """Base case providing a scratch directory for generated slice files."""

    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.tmp = Path(tmp.name)

    def write_file(self, name, text):
        path = self.tmp / name
        path.write_text(text, encoding="utf-8")
        return path


class PlainGcodeParsingTests(TempDirTestCase):
    """Plain .gcode files carrying inline slicer header/footer comments."""

    def test_cura_header_and_footer_comments(self):
        path = self.write_file("part.gcode", CURA_GCODE)
        meta = gcode_parser.parse_file(path)
        self.assertEqual(meta.file_name, "part.gcode")
        self.assertEqual(meta.material, "UNKNOWN")
        self.assertAlmostEqual(meta.grams, 17.01, places=4)
        self.assertEqual(meta.length_mm, 5670.0)
        self.assertEqual(meta.duration_seconds, 3031)

    def test_cura_grams_derived_from_length_constant(self):
        path = self.write_file("part.gcode", CURA_GCODE)
        meta = gcode_parser.parse_file(path)
        expected = meta.length_mm / 1000.0 * gcode_parser.GRAMS_PER_METER_DEFAULT
        self.assertAlmostEqual(meta.grams, expected, places=4)

    def test_prusaslicer_footer_comments(self):
        path = self.write_file("part.gcode", PRUSASLICER_GCODE)
        meta = gcode_parser.parse_file(path)
        self.assertEqual(meta.material, "PLA")
        self.assertEqual(meta.grams, 4.49)
        self.assertEqual(meta.length_mm, 1500.5)
        self.assertEqual(meta.duration_seconds, 5415)

    def test_orcaslicer_footer_comments(self):
        path = self.write_file("part.gcode", ORCASLICER_GCODE)
        meta = gcode_parser.parse_file(path)
        self.assertEqual(meta.material, "PETG")
        self.assertEqual(meta.grams, 8.25)
        self.assertEqual(meta.length_mm, 2750.0)
        self.assertEqual(meta.duration_seconds, 8130)

    def test_bambu_studio_footer_comments(self):
        path = self.write_file("part.gcode", BAMBU_STUDIO_GCODE)
        meta = gcode_parser.parse_file(path)
        self.assertEqual(meta.material, "PLA")
        self.assertEqual(meta.grams, 10.31)
        self.assertEqual(meta.duration_seconds, 4205)

    def test_gcode_without_metadata_raises_exact_error(self):
        path = self.write_file("bare.gcode", BARE_GCODE)
        with self.assertRaises(gcode_parser.MissingMetadataError) as ctx:
            gcode_parser.parse_file(path)
        self.assertEqual(
            str(ctx.exception),
            "no filament weight or length metadata found in bare.gcode",
        )

    def test_gco_extension_is_accepted(self):
        path = self.write_file("part.gco", PRUSASLICER_GCODE)
        meta = gcode_parser.parse_file(path)
        self.assertEqual(meta.grams, 4.49)


class ArchiveParsingTests(TempDirTestCase):
    """Synthetic .3mf and .gcode.3mf ZIP archives built in memory."""

    def build_archive(self, name, entries):
        # Generate the ZIP payload in memory, then persist it for parse_file.
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w") as archive:
            for entry_name, content in entries.items():
                archive.writestr(entry_name, content)
        path = self.tmp / name
        path.write_bytes(buffer.getvalue())
        return path

    def test_3mf_with_metadata_embedded_gcode(self):
        path = self.build_archive(
            "plate.3mf",
            {
                "3D/3dmodel.model": "<model/>",
                "Metadata/plate_1.gcode": CURA_GCODE,
            },
        )
        meta = gcode_parser.parse_file(path)
        self.assertEqual(meta.file_name, "plate.3mf")
        self.assertAlmostEqual(meta.grams, 17.01, places=4)
        self.assertEqual(meta.duration_seconds, 3031)

    def test_gcode_3mf_with_root_level_gcode(self):
        path = self.build_archive(
            "part.gcode.3mf",
            {
                "3D/3dmodel.model": "<model/>",
                "part.gcode": PRUSASLICER_GCODE,
            },
        )
        meta = gcode_parser.parse_file(path)
        self.assertEqual(meta.file_name, "part.gcode.3mf")
        self.assertEqual(meta.material, "PLA")
        self.assertEqual(meta.grams, 4.49)
        self.assertEqual(meta.duration_seconds, 5415)

    def test_metadata_gcode_is_preferred_over_root_level(self):
        path = self.build_archive(
            "plate.3mf",
            {
                "plate.gcode": "; filament used [g] = 1.00\n",
                "Metadata/plate_1.gcode": "; filament used [g] = 9.00\n",
            },
        )
        meta = gcode_parser.parse_file(path)
        self.assertEqual(meta.grams, 9.00)

    def test_archive_without_gcode_raises_exact_error(self):
        path = self.build_archive("empty.3mf", {"3D/3dmodel.model": "<model/>"})
        with self.assertRaises(gcode_parser.MissingMetadataError) as ctx:
            gcode_parser.parse_file(path)
        self.assertEqual(
            str(ctx.exception), "no embedded .gcode stream found in empty.3mf"
        )

    def test_corrupt_archive_raises_value_error(self):
        path = self.tmp / "corrupt.3mf"
        path.write_text("this is not a zip archive", encoding="utf-8")
        with self.assertRaises(ValueError) as ctx:
            gcode_parser.parse_file(path)
        self.assertEqual(str(ctx.exception), f"invalid 3mf archive: {path}")


class UnsupportedFormatTests(TempDirTestCase):
    """parse_file must reject unsupported extensions and missing files."""

    def test_stl_extension_rejected_with_exact_error(self):
        path = self.write_file("model.stl", "solid model")
        with self.assertRaises(gcode_parser.UnsupportedFormatError) as ctx:
            gcode_parser.parse_file(path)
        self.assertEqual(str(ctx.exception), "unsupported file format: .stl")
        self.assertIsInstance(ctx.exception, ValueError)

    def test_extensionless_file_rejected_with_file_name_in_error(self):
        path = self.write_file("README", "plain text")
        with self.assertRaises(gcode_parser.UnsupportedFormatError) as ctx:
            gcode_parser.parse_file(path)
        self.assertEqual(str(ctx.exception), "unsupported file format: README")

    def test_missing_file_raises_file_not_found(self):
        path = self.tmp / "absent.gcode"
        with self.assertRaises(FileNotFoundError) as ctx:
            gcode_parser.parse_file(path)
        self.assertEqual(str(ctx.exception), f"file not found: {path}")


if __name__ == "__main__":
    unittest.main()
